### ISSUE TITLE
Outline larger than button

### ISSUE THREAD

**Issue by Koraydi** [xod-wow/LiteButtonAuras#10]
Hi Im having an issue in prepatch where the colour outline is way larger than the button its attached to creating these large squares all over.
Im not getting any LUA errors related to the addon

![image](https://user-images.githubusercontent.com/91707942/198242833-34e3f3c8-142e-48c6-9dcc-506461be2b59.png)

**Comment by mbattersby** [comment]
Someone else reported this once but never replied with any details (and obviously it doesn't happen for me).

LBA doesn't set the size, it just attaches the overlay directly over the button.

Do you have some other addon (or weakaura) that is affecting the action button stylings or size?

Are you using an action bar addon?

Are you using Masque? If so what Skin, and do you have LBA set to the same skin as your bars?

Does it happen with no other addons but LBA loaded?

**Comment by Koraydi** [comment]
It was 100% Masque mucking things up. Even though I didnt have the main Masque enabled it seems that one of the icon packs was messing with it still. Sorry for taking up your time

**Comment by mbattersby** [comment]
All good. Do you know which masque addon pack it was? Might save me some time next time someone has the problem.

**Comment by Koraydi** [comment]
These are the Masque packs I had "enabled" but technically werent loaded due to the main Masque addon being disabled 
![image](https://user-images.githubusercontent.com/91707942/198478608-df03ac43-fb2d-484c-b169-a579e33997f5.png)

**Comment by mbattersby** [comment]
Thanks again, appreciate your extra help.

**Comment by mbattersby** [comment]
I looked into this a bit more (I expect you don't care but in case anyone else looks at this ticket or I have to revisit it).

It seems to be a bug in Masque where skins that don't handle SpellHighlight (such as the default "Classic" skin) are calling ClearAllPoints() on the texture anyway. 10.0.2 has a workaround for some of this to make the default behaviour a bit nicer.

I really hate having to adjust my addons for Masque's weirdnesses, but that's life.
