### ISSUE TITLE
Icons sometimes enlarging and not resetting (version 10.0.7)

### ISSUE THREAD

**Issue by sthdevilish** [xod-wow/LiteButtonAuras#13]
Noticed this recently. Some skills/icon that have border glow active would get enlarged, thus obscuring other action bar slots. This seems to happen randomly, with different skills and circumstances, but sometimes stays that way for a long time during fight.

![](https://i.imgur.com/DChL02v.png)

**Comment by mbattersby** [comment]
I don't know what addon is doing that, but it's not LiteButtonAuras. It doesn't change the size of anything ever.

Some other addon must be either doing it or messing it up.

**Comment by sthdevilish** [comment]
I'm sorry, this is indeed not caused by LBA. In fact, it's not caused by any addon at all, as I just tested it on the DF beta with no addons, default settings, and it would still happen... 

I even found a way to reproduce it: for me it happens with macros that contain a skill (on nomod press) that has a border glow with a specific buff proc. When you quickly press modifier while the button is glowing, it could get enlarged and stuck for a few seconds...

So, ugh, yeah... Welcome to paid beta testing I guess -.- Shame on you Blizzard.

**Comment by mbattersby** [comment]
Wow, that's annoying! Appreciate you letting me know.
