### ISSUE TITLE
Countdown Timers for Certain Channeled Abilities

### ISSUE THREAD

**Issue by Pillgar** [xod-wow/LiteButtonAuras#18]
Was thinking it would be nice to have countdown timers for channeled abilities while they're being channeled.  Like Mind Flay for example.  I couldn't figure out how to add it manually.  Great addon BTW!!!!

**Comment by mbattersby** [comment]
I'm not sure what you mean by countdown timers, do you mean the channel time?

That's more of a cast bar thing, I'm not going to add something like that because I feel it belongs on the cast bar not on the button.

**Comment by Pillgar** [comment]
ya, a channel countdown time.  I do see it on my cast bar, it'd just be nice to have that visual on the botton to maintain continuity with the other visuals this addon brings.

**Comment by mbattersby** [comment]
Thanks for the suggestion, but this is not something I'm going to put into LBA. Perhaps another addon could put more cast bar things into the actionbuttons.
