### ISSUE TITLE
No shadows when font != default

### ISSUE THREAD

**Issue by aspiringnobody** [xod-wow/LiteButtonAuras#21]
If I set the the font to anything other than /lba font default the shadow the makes the text readable on light backgrounds disappears.

**Comment by mbattersby** [comment]
Seems like a bug. Can you give an example of your setting and I'll check it out.

**Comment by mbattersby** [comment]
For me it seems to obey the outline or not setting from the font.

e.g. `/lba font GameFontNormal` has no outline, but `/lba font GameFontNormalOutline` has an outline.

**Comment by mbattersby** [comment]
Thanks, I'll put something in the docs about it too.

**Comment by mbattersby** [comment]
README updated with some info about fonts.
