### ISSUE TITLE
is their a way for you to mantain adibuttonauras? 

### ISSUE THREAD

**Issue by xapollyon** [xod-wow/LiteButtonAuras#22]
I was trying to see if i can fix simple things in adibuttonauras, and realized that it I have no clue whats going on

although in the files adi has mentioned anyone is free to take over, was wondering if you can do something for that adi addon?

**Comment by mbattersby** [comment]
Sorry, I have no interest in (or time for) doing that. I'd suggest posting an issue in the AdiButtonAuras issues looking for someone to help. There is also a WoW Addons discord that might have someone with advice https://discord.gg/ArxzqcaN

**Comment by xapollyon** [comment]
Thank you for your reply, I thought I would ask and and you have made a great lite addon and I appreciate it and you.

Is there a way to make the counter numbers  larger? - I dont see an config option in litebuttons

**Comment by mbattersby** [comment]
You can change the font size:
```
/lba font Size16
```

All of the options are described on in the README https://github.com/xod-wow/LiteButtonAuras
