### ISSUE TITLE
I get this on my Warlock when switching pet to passive during combat

### ISSUE THREAD

**Issue by Shackles70** [xod-wow/LiteButtonAuras#25]
2x [ADDON_ACTION_BLOCKED] AddOn 'LiteButtonAuras' tried to call the protected function 'PetActionButton1:SetShown()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `SetShown'
[string "@FrameXML/ActionBar.lua"]:196: in function `UpdateShownButtons'
[string "@FrameXML/PetActionBar.lua"]:77: in function <FrameXML/PetActionBar.lua:70>
[string "=[C]"]: ?
[string "=[C]"]: in function `CastPetAction'
[string "@FrameXML/PetActionBar.lua"]:257: in function <FrameXML/PetActionBar.lua:250>
[string "=[C]"]: ?

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}

**Comment by mbattersby** [comment]
Does this happen with only LiteButtonAuras loaded?

**Comment by mbattersby** [comment]
Can't reproduce this at all. Most likely another addon also using AceDB or CallbackHandler embeds doing something wrong and LiteButtonAuras getting blamed.

**Comment by Shackles70** [comment]
Ok thanks for looking into it for me. Probably some conflict that will fix
itself.

**Comment by mbattersby** [comment]
I've found a blizzard bug that I think is causing this. I'll see if I can figure out a work-around.

**Comment by Shackles70** [comment]
Ok, thanks for the update.
