### ISSUE TITLE
Add an option to have timers display in only one colour.

### ISSUE THREAD

**Issue by arcadepro** [xod-wow/LiteButtonAuras#3]
Not a fan of the gradient colour timers myself so if you could add an option to not use it or set a fixed colour it would be cool.

**Comment by mbattersby** [comment]
This is pretty straightforward, the issue is the 100 hours it will take to make a GUI for options. Perhaps I should just give up and use AceConfig or whatever the awful thing is called.

**Comment by mbattersby** [comment]
9.1.4 adds a slash command and

`/lba colortimers on|off`

**Comment by arcadepro** [comment]
I'm 100% fine with no gui :D hated adding them to my own addons. So I just stopped.

**Comment by mbattersby** [comment]
\o/

Closing this for now, I'll add it to the GUI if there ever is one.
