### ISSUE TITLE
Errors with Button Forge

### ISSUE THREAD

**Issue by Shackles70** [xod-wow/LiteButtonAuras#32]
This addon hates it when I have Button Forge enabled. I can't copy the flooding of errors I get in Bugsack because it just instantly clears my selection. Not sure if it has something to do with an item I have in the bar or what.
I've reverted back to Adibuttonauras for now. Just letting this be known. It could very well be some other combinations of my addons.

**Comment by mbattersby** [comment]
I just installed button forge on retail to test, no errors working fine displaying the auras.

**Comment by mbattersby** [comment]
![image](https://github.com/user-attachments/assets/5fef9862-c1c8-4d5e-a1a2-05c3cbb36455)

bufo bar to the left

**Comment by mbattersby** [comment]
Any other hints about what's causing your issue?

**Comment by Shackles70** [comment]
I will move buttons from Button Forge and see if it's trying to interact with a spell or item I have in them.

**Comment by Shackles70** [comment]
Ok it seems macros and scripts in Button Forge are causing the errors. I had a /roll macro, /note macro and a script to tell me how many Catalyst charges I have. as soon as I took them off no errors. 
I also have another addon called select which makes kind of a selective macro that will error on reload and didn't spam so I was able to copy it. 
I know there was some kind of thing with macros in the game with addons. I also use Opie and it will not work on my druid for mounts because it has an internal /cancelform or something, but also anything that opens with a macro in Opie will not work.
I will remove my macros from Button Forge to stop the errors.
I hope I explained this to where it can be understood. 
Fantastic addon I'm glad I can use it again now. 
If this error is something you think I should the author of Button Forge know about let me know. I do know that the macros work fine tho without Lite Button Auras enabled. 

20x bad argument #1 to '?' (Usage: local name = C_Spell.GetSpellName(spellIdentifier))
[string "=[C]"]: in function `GetSpellName'
[string "@LiteButtonAuras/Overlay.lua"]:157: in function `SetUpAction'
[string "@LiteButtonAuras/Overlay.lua"]:209: in function `Update'
[string "@LiteButtonAuras/BarIntegrations.lua"]:122: in function <LiteButtonAuras/BarIntegrations.lua:122>
[string "=[C]"]: in function `SetTexture'
[string "@ButtonForge/Button.lua"]:1485: in function `DisplayActive'
[string "@ButtonForge/Button.lua"]:799: in function `SetEnvMacro'
[string "@ButtonForge/Button.lua"]:640: in function `SetCommandExplicitMacro'
[string "@ButtonForge/Button.lua"]:583: in function `SetCommandMacro'
[string "@ButtonForge/Button.lua"]:2131: in function `RefreshMacro'
[string "@ButtonForge/Util.lua"]:2459: in function `RefreshMacros'
[string "@ButtonForge/EventManager.lua"]:261: in function <ButtonForge/EventManager.lua:228>

Locals:
(*temporary) = "bad argument #1 to '?' (Usage: local name = C_Spell.GetSpellName(spellIdentifier))"

**Comment by mbattersby** [comment]
Thanks! I'm not sure what the cause is but I'll figure out a workaround. Something must have changed in ButtonForge and macros for TWW.

**Comment by Shackles70** [comment]
This is what was posted in the Opie error page.

[Patch 11.0.0] Mount slices do not work for Druid characters
OPie internally uses a macro to reliably cancel certain shapeshift forms before attempting to summon a mount. Due to the Blizzard-imposed restrictions on macro execution in patch 11.0.0, OPie is not able to run any macros at the moment, causing mount slices to fail to do anything for Druids.

**Comment by mbattersby** [comment]
I have a fix that stops it from having an error, but out of curiousity are you able to post a macro that causes the error?

**Comment by mbattersby** [comment]
All good I figured it out. Please try LiteButtonAuras 11.0.0-3.

**Comment by Shackles70** [comment]
Thanks friend. I will give it a go tomorrow.
