### ISSUE TITLE
Totems don't respect ignore filter

### ISSUE THREAD

**Issue by MustachioNut** [xod-wow/LiteButtonAuras#34]
Totem duration is displayed on buttons due to default matching even after the totem has been added to the ignore list. 

Tested Healing Stream Totem, Earthgrab Totem and Capacitor Totem on Resto Shaman. Ty for LBA.

**Comment by mbattersby** [comment]
That's definitely a bug. I'm away on vacation at the moment but I'll fix it up when I return next week.

**Comment by mbattersby** [comment]
Fixed in 11.0.5-1, cheers.
