### ISSUE TITLE
[Enhacement] LibDataBroker/Minimap support

### ISSUE THREAD

**Issue by Dajova** [xod-wow/LiteButtonAuras#35]
I'd love to be able to access the options to add new spells without having to access the options everytime i wanna add/change a aura or something, like a databroker or minimap icon. Worth considering, at least.

**Comment by mbattersby** [comment]
You can open the options directly with `/lba options` or `/lba opt` slash command in chat.

I'll see if I can add something to the AddOn compartment. Not really keen to use an entire broker or minimap button just to open the options.

**Comment by mbattersby** [comment]
Will appear in the Addon Compartment as of 11.0.5-2

![image](https://github.com/user-attachments/assets/aeb43f3c-aacf-4923-8dc3-4909fc87492c)
