### ISSUE TITLE
Allow the user to select which font is used.

### ISSUE THREAD

**Issue by arcadepro** [xod-wow/LiteButtonAuras#4]
Perhaps define which font (and size) to be used in the options file so people can change it.

**Comment by mbattersby** [comment]
I suspect this is probably beyond me.

**Comment by arcadepro** [comment]
It was just a thought as the timers were a little too small on thin on my screen.

Perhaps for the moment you could simply add some variables to the options file like:
fontpath="Fonts\\FRIZQT__.TTF"
size=14
style="OUTLINE"

then use self.Timer: SetFont (fontpath, size, style) in overlay.lua.

Anyone wanting a different font can hack it in without going down the sharedmedia rabbithole for now.

**Comment by mbattersby** [comment]
Are you able to send a screenshot of how the timer looks for you?

There's not much room on the button once there are stacks and the cooldown number. Anything with stacks the cooldown is bumping up against it for me already with GameFontNormal.

I'm not averse to the option, but my first preference is a default that works for everyone.

**Comment by mbattersby** [comment]
![image](https://user-images.githubusercontent.com/1300207/133540723-040308ab-22c2-4f93-aa49-63943cfa569c.png)

This is an example of stack + low timer on my bars.

**Comment by arcadepro** [comment]
Yeah, mine looks simlar to yours by default. 

I tinkered with my local version to use no gradient/14pt/outline and %d formatting for short timers instead of .1f. I find the decimal point display a bit overkill on a small button. 

![image](https://user-images.githubusercontent.com/1977760/133547889-e8af396c-4410-4e02-ac35-9f787e1e64af.png)

**Comment by mbattersby** [comment]
I looked at ABA - I copied most of the style from it since it's what I've been using for a decade. Their default is tenths of a second below 3 seconds, so that's what I did also as my ABA config is pretty much default. I use the tenths a lot, I tend to be a interrupt-at-the-last-second kind, and also try to max out my chi torpedo run speed increase. :)

I think there is a good argument for a "tenths  or not" option, since that is something people can reasonably differ on.

The font stuff I will have to think about more.

**Comment by mbattersby** [comment]
8537a4f9 adds /lba decimaltimers on|off

**Comment by mbattersby** [comment]
The problem with the font is not that its hard to set (it's not) but that for it to be dynamic there has to be a complete reskin action of all the already created buttons, and some kind of event that triggers it when the option is changed.

And the event requires that the rest of the code no longer sets the db options directly, but calls some kind of getter/setter function wrapper to do it, which is a massive annoyance.

I really wish AceDB had an OnProfileModified event or something. I'm sick of DIY all the time. :(
