### ISSUE TITLE
Friendly players trigger the kick alert.

### ISSUE THREAD

**Issue by arcadepro** [xod-wow/LiteButtonAuras#5]
Friendly players trigger the kick alert when targetted while they are casting. Need to check if targets are friendly or not. 

This issue might also apply to the other warnings (purge, soothe, etc, these cases are unchecked).

**Comment by mbattersby** [comment]
Good catch.

Interesting, I expected cantInterrupt from UnitCastingInfo() to be false in that case but it seems it's not. The aura stuff is an error from when I took out the friendly dispels, but it's good as it's pointed out I don't need to fetch all the helpful buffs on friendly targets.

**Comment by mbattersby** [comment]
Fixed in ffb8ce6 (hopefully)
