### ISSUE TITLE
Offensive dispel highlight on targetted enemies does not work. 

### ISSUE THREAD

**Issue by arcadepro** [xod-wow/LiteButtonAuras#7]
Tested with Shaman's Purge in many M+ dungeons. (Nightcloak Fencer mob in Revendreth (48,30) also as a test case.)

**Comment by mbattersby** [comment]
I think I just totally forgot purge out of the list of hostile dispels.

**Comment by mbattersby** [comment]
I don't think I have a way to test this easily so please let me know if it's working.

**Comment by arcadepro** [comment]
Works on Shaman now, yes. 

The coloured border is a little muted (when it's magic). Maybe change the alpha to 0.9 over 0.7 but this is a minor thing.

**Comment by mbattersby** [comment]
Thanks, I've opened a new issue #8 for that, as I agree.
