### ISSUE TITLE
1.14.0 support (private server)

### ISSUE THREAD

**Issue by kalypto89** [xod-wow/LiteButtonAuras#9]
Hello;
I know this version is for classic wotlk but is it possible to enable support for 1.14.0 version?
Currently there is no highlight on the action buttons for target (for either buffs on friendly or debuff on enemy).
the addon only works for your own buffs on yourself
![image_2022-10-21_130328742](https://user-images.githubusercontent.com/116260914/197170346-ee92b5ff-c42b-433b-b4fb-262b181e3905.png)

![image](https://user-images.githubusercontent.com/116260914/197178317-38e988b0-35cc-4c0f-a0ca-92f23840d9b6.png)

If you can't support for this version, could you please advise the code lines to alter?
I'm not anywhere near a developer or skill, but I understand that my request is quite particular so maybe it's something I can do on my own otherwise.

**Comment by mbattersby** [comment]
Your first screenshot "my friendly buff on target" is not something that LBA does, so it's expected that it doesn't show. LBA only shows friendly buffs on player, other friendly units are better handled by unit frame addons.

The second one should work. As far as I can tell it works for me. See screenshot below of a level 2 warlock I made on WoW Classic (not season of mastery) showing Immolate highlighting on my bar according to the debuff on my target.

![image](https://user-images.githubusercontent.com/1300207/197315855-1125f0f2-9c3d-409c-b2aa-1f95b816b41d.png)

What's different between what I've done and what you're doing? Does it work with the default actionbars? Do the spell names and the buff names not match for these spells? Do you have any other suggestion on how I can test it when I don't play classic (and aren't going to spend hundreds of hours leveling)?

**Comment by mbattersby** [comment]
I just noticed that was a SoM realm. I'll try again on non-SoM just in case.

**Comment by mbattersby** [comment]
Re-tested on regular (not Season of Mastery) realm. Same result, seems to be working for me.

**Comment by kalypto89** [comment]
hey, thank you for the reply and for looking into this.
I mentioned this in the title but maybe I wasn't specific; I think this works for me on both SoM and classic era; however the version im working on right now is 1.14.0  pls see screenshot. this is used via hermes proxy to be able to play 1.14.0 classic client emulated on a vanilla server 1.12.
I was wondering if you are able to test for this? Or again maybe advise some code that I could have changed.
Sorry I know this is very specific, but your add-on is a huge QoL improvement especially for playing warlock 
![image](https://user-images.githubusercontent.com/116260914/197359056-832d5b0a-1ac9-4144-932b-8c2f4d7082ec.png)

**Comment by mbattersby** [comment]
Ah, I see!

My best guess is that this is probably a bug in Hermes Proxy.

The UnitAura() API call to fetch buffs and debuffs didn't exist in WoW 1.12 (didn't come in until 3.0.2 I think), also there were spell ranks in the UnitBuff() and UnitBuff() return values which were removed at the start of BfA retail and also aren't there in the Classic client.

So Hermes Proxy must be doing something to handle these differences. Maybe not 100% right.

First thing to check would be to see if the aura query is working. Put up one DoT on a target and do: `/dump UnitAura('target', 1, 'HARMFUL PLAYER')` and see if it prints the debuff. Most obvious problem would be that nothing comes up because they aren't handling 'HARMFUL PLAYER' properly'. If it shows nothing you probably should log that as a bug with Hermes Proxy on github. You can also test if `/dump UnitDebuff('target', 1, 'PLAYER')` works instead.

What it should show is 15 values as per https://wowpedia.fandom.com/wiki/API_UnitAura

<img width="140" alt="image" src="https://user-images.githubusercontent.com/1300207/197364734-17b17ded-5794-477f-996f-4c8d5ba947af.png">

If it shows a different number of values that would be interesting too, or if the [2] value is a small number or 0 or missing indicating that they have left the spell rank in their incorrectly.

**Comment by kalypto89** [comment]
Hi there, first of all thanks for the support here. I followed your instructions and neither of the queries from above listed any result - please see the screenshot.
![image](https://user-images.githubusercontent.com/116260914/197383558-dc00adab-36e5-4f51-ae53-e6105c5cd4d5.png)

Does this mean I should log the bug with HermesProxy instead? Thank you.

**Comment by kalypto89** [comment]
Hey, I noticed that the debuff is also not showing on NeatPlates. Not sure if you are familliar with this add-on but the add-on shows your debuffs above the enemy target nameplates so maybe it is quering the same code as your addon?

So its not showing the debuff please see below:
![image](https://user-images.githubusercontent.com/116260914/197383955-8ffa22ef-1e72-41d4-b55e-c74210076162.png)

But another addon, called Nameplate Auras will show the debuff, but only if the aura name is manually loaded as show in this screenshot.
![image](https://user-images.githubusercontent.com/116260914/197384101-ac64d998-44a1-4a7f-ac87-1b6b0bd82c9e.png)
![image](https://user-images.githubusercontent.com/116260914/197384157-45d28da3-5292-4833-aab2-3ed6c4b926ca.png)

Not sure this information helps you but I was thinking that maybe the source where NameplateAuras is querying would help in determining where the error comes from/or what could be changed in neatplates / litebuttons to help detect and display the debuff?
Also strange that it only works in nameplateaura when the spell is manually loaded in the addon interface but not before.

**Comment by mbattersby** [comment]
Reading the response to the HermesProxy issue, it seems like the 1.12 private server has no way to determine which buffs are cast by you at all.

You can go through Controller.lua in the LBA code and remove the PLAYER and RAID from all of the ForEachAura calls (should be 5 places). Then you can see the auras, but they will display if anyone cast them not just you. That appears to be the only thing possible in the 1.12 server – what LBA relies on  to work just isn't there.

Sorry, looks like you're plain out of luck and it's just not possible to do in 1.12.

**Comment by kalypto89** [comment]
hello.
well your suggestion did the trick.
better than nothing i guess, still helps alot!
see the result:
![image](https://user-images.githubusercontent.com/116260914/197396237-80529f83-ec10-4475-b2fe-896b96282be1.png)
thank you so much for your help, you've been asweome!

**Comment by mbattersby** [comment]
Most welcome. I've never known anything about private servers before so it was an interesting thing to look at.

**Comment by kalypto89** [comment]
Oh sorry - just one more thing!
shouldn't it also show the duration of the debuff in the nameplate?
Thanks!
![image](https://user-images.githubusercontent.com/116260914/197480067-675f6bcf-0b31-4750-b6b3-b5713d39964f.png)

**Comment by mbattersby** [comment]
Niether Vanilla nor Classic provide debuff durations – in the case of Classic by deliberate decision from the developers to take them out of the code. So the expiryTime field in the UnitAura return is always empty.

I think most of the addons that support timers are using the UnitAura wrapper from [LibClassicDurations](https://www.curseforge.com/wow/addons/libclassicdurations).

If you install that you can probably put something like this at the top of Controller.lua:

```lua
local LibClassicDurations = LibStub("LibClassicDurations", true)
```

and then replace
```
local UnitAura = UnitAura
```
with
```
local UnitAura = LibClassicDurations.UnitAuraWrapper
```

**Comment by kalypto89** [comment]
ill try it out and let you know. right now i can tell you for sure that weakauras for example populates the debuff duration on target. thanks for the tip, ill keep u updated!

**Comment by mbattersby** [comment]
Ha, well the fact it works is proof at least one of your other addons is using LibClassicDurations, because it needs a bit of a tweak to work without one.

```lua
local LCD = LibStub("LibClassicDurations", true)
if LCD then LCD:Register("LiteButtonAuras") end
```

I also had to modify the LiteButtonAuras.toc to add LibClassicDurations to the OptionalDeps line

**Comment by mbattersby** [comment]
I checked and WeakAuras2 is using LibClassicDurations for this as well. :)

**Comment by mbattersby** [comment]
Out of interest, one of the other return values from UnitAura is "isCastByPlayer" (field 13). I wonder if it's filled out in Hermes Proxy which would be a way around the "PLAYER" filter. I suspect not but if you feel like trying the DoT test again and running
```
/dump UnitAura('target', 1, 'HARMFUL')
```
I'm curious if [13] has anything in it.

**Comment by kalypto89** [comment]
sure, no worries - anything to help;
here you go

![image](https://user-images.githubusercontent.com/116260914/197729342-702b3c18-aa93-4ec2-9d56-fa707e55f925.png)

**Comment by kalypto89** [comment]
sure no worries, happy to help!
here you go 
![image](https://user-images.githubusercontent.com/116260914/197729639-a6815e15-2e3f-4df3-bccf-08e9c0b7d55b.png)

**Comment by mbattersby** [comment]
Nothing there, ah well. Best we can do with 1.12.
